ENH: Link emperor double-click event and add timer cancelation
biocore/empress pull request #370
Opened 2020-09-03 17:08 UTC by ElDeveloper

This adds the ability to double-click on a color category in Emperor and highlighting the tips in the tree represented by that group. This also adds a timer cancellation to prevent problems with sample selections as reported in #197.

![double-click](https://user-images.githubusercontent.com/375307/92145140-a4125e80-edcc-11ea-8f90-65db9e7536ec.gif)

The documentation on the callback is fairly lax but should be improved once the explanation in #319 is merged.

2020-09-03 17:08 UTC, ElDeveloper commented
HT to @antgonza for the idea 👍

2020-09-03 17:18 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F370%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F370%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F370%2Fempress-tree.qzv)

2020-09-04 21:10 UTC, fedarko requested changes
Thanks @ElDeveloper! This functionality is really handy.

Notes from review:

1. It looks like double-clicking on biplot color categories causes an error: this is what pops up in the console when I double-click the purple (`p__Proteobacteria`) Level 2 category:
   ![purp](https://user-images.githubusercontent.com/4177727/92283360-90dabe00-eeb4-11ea-916e-d18fb19c4c53.png)
   It looks like the code is trying to treat feature IDs as sample IDs, which causes the problem. I suppose ideally there would be some fancy interaction event where all nodes in this feature metadata group would be selected / colored in Empress or something, but the easiest way to handle this for now would probably just be detecting that a biplot category was selected and not doing anything.

2. I haven't been able to figure out exactly *why* this is happening, but it seems like there are still some #197-ish bugs that can occur:
   ![eitherbugsorimgoingcrazy](https://user-images.githubusercontent.com/4177727/92283820-94bb1000-eeb5-11ea-8e0c-35d1a3a691ab.gif)

   One variant of these problems is reproducible when you double-click on `gut`, then select all `gut` samples: when this happens the samples remain highlighted --
   ![gutgutgut](https://user-images.githubusercontent.com/4177727/92284804-b5846500-eeb7-11ea-9466-430fc95700d4.gif)
   This also seems to be doable with `tongue` samples, as well as doable in the opposite order (select all `gut` samples then double-click on `gut`, resulting in the samples remaining highlighted indefinitely) --
   ![gut2gut](https://user-images.githubusercontent.com/4177727/92285038-2f1c5300-eeb8-11ea-9e06-4d3eb299593f.gif)
   Not a very important issue, since I think at this point these problems only really show up when you try to break things :), but it would be nice to at least document these as we make this stuff more and more robust.

2020-09-14 17:46 UTC, ElDeveloper commented
@fedarko thanks for the review, I think these bugs are addressed. Let me know if you get a chance to try this out.

2020-09-15 23:13 UTC, fedarko approved these changes
@ElDeveloper Thanks so much, looks good to me!

2020-09-16 19:49 UTC, merged

2020-09-16 19:50 UTC, fedarko commented
Thanks @ElDeveloper! :point_up_2: :point_up_2: :timer_clock:

2020-09-16 19:52 UTC, ElDeveloper commented
Thanks so much @fedarko!

On (Sep-16-20|12:50), Marcus Fedarko wrote:
>Thanks @ElDeveloper! :point_up_2: :point_up_2: :timer_clock:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://urldefense.com/v3/__https://github.com/biocore/empress/pull/370*issuecomment-693629147__;Iw!!Mih3wA!Rqy5aiCsaaNj1NSU9VfWgsznb-8BlVK6XV8mqYMVUEGNJkNtShWaoa9K_MGV0Y0$