Support creating a visualization without a table / sample metadata
biocore/empress pull request #375
Opened 2020-09-10 02:02 UTC by fedarko

Closes #175. This splits up `qiime empress plot` into two visualizers:

1. `qiime empress community-plot` (requires a tree, table, and sample metadata with feature metadata optional; analogous to the current `plot` visualizer)
2. `qiime empress tree-plot` (just requires a tree, with feature metadata optional)

The reason for making two separate visualizers (rather than just making the table / sample metadata optional) is that both the table and sample metadata are needed to make the other useful, and this seems like a more elegant solution to me than leaving things as one command and doing the user-facing checking ourselves. (See #175 for discussion.)

Depending on the amount of data passed to Empress, the amount of stuff shown in Empress' side panel is modified (so if `qiime empress tree-plot` is used, the `Sample Metadata Coloring` and `Animation` tabs aren't shown, along with some other stuff). This sort of thing was already being done dependent on whether or not the user passed feature metadata to Empress, but:

1. now it is formalized (elements in the empress HTML can have `needs-metadata`, `needs-community-data`, or `needs-feature-metadata` classes which are used to hide arbitrary amounts of elements at once; so we can do things like hide certain sections in  the Tree Properties panel if needed)
2. now, the side panel starts off as hidden and is shown after figuring out the stuff above, so there isn't e.g. a moment where the panel is visible but the feature metadata tab isn't visible yet (which is currently the case with Empress if feature metadata is passed)

This PR also makes a few other changes, including adding two QZVs to the `make docs` command / McHelper and allowing other types of `FeatureTable`s besides `FeatureTable[Frequency]` to be passed.

2020-09-10 02:15 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F375%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F375%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F375%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F375%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F375%2Fplain.qzv)

2020-09-11 16:19 UTC, ElDeveloper commented
@ebolyen this PR should address the issue of needing a feature table in order to use Empress. If you can try this out that would be very helpful!

2020-09-15 19:23 UTC, antgonza commented
Really cool! Just tested without feature metadata:
- a 928,024 tip tree (DeblurReferencephylogenyforSEPPGreengenes138Trimminglength125/insertion_tree.relabelled.tre) via qiime2-2020.8 and everything was smooth considering the size : qzv was created in under 2 min, opening the qzv (13M) was pretty nice and handling was OK.
- a 6,980,235 tip tree (DeblurReferencephylogenyforSEPPGreengenes138Trimminglength90/insertion_tree.relabelled.tre) didn't work as smoothly : qzv was created in ~6 min (wow! - impressive!), opening the qzv (85M) : Firefox, just quit; Chrome/Safari started to load (circle with loading message appeared), Safari quit with the Q2 "Expired Page" message, Chrome never changed state ... 

Other comments (fine to add new issues if you see fit):
- Chrome seems to still perform worst than Safari (takes longer to open and to change layouts)
- When changing layouts it would be good to change the cursor to a waiting/processing pointer and ignore all interactions as a user (me) can continue clicking and changing layouts until the browser brakes

2020-09-15 19:32 UTC, kwcantrell commented
@antgonza thanks for testing this out! I have a feeling that part of the reason the .qzv fails for the large tree has to do with the size of the buffer data we are trying to pass to webgl. I am working on two branches that will greatly reduce the amount of data passed to the buffers. So, hopefully once those are merged in, we can load the ~6.9 million tip tree.

2020-09-15 19:38 UTC, fedarko commented
Awesome, thanks @antgonza! Agreed with Kalen; it'd be awesome if we could get that working, and I suppose almost 1 million is already pretty solid :)

The chrome issue is documented at #338, and I just opened a new issue for the "waiting" issue at #381.

2020-09-25 18:47 UTC, ElDeveloper requested changes
All looks good, just a couple of suggestions, and I think the `Export Legend as SVG` button needs to be hidden when no metadata is present (to be consistent with the rest of the UI not showing irrelevant options).

2020-09-25 18:47 UTC, ElDeveloper commented on empress/core.py
> +        information is available.)
```suggestion
        ValueError. If both are None, then the values of the ordination,
        ignore_missing_samples, filter_extra_samples, filter_missing_features,
        and shear_to_table arguments will be ignored since no sample
        information is available.
```

2020-09-25 18:47 UTC, ElDeveloper commented on empress/support_files/templates/side-panel.html
> +     merged in.
Looks like this comment is out of date isn #363 is already merged.

2020-09-25 22:45 UTC, fedarko commented on empress/support_files/templates/side-panel.html
> +     merged in.
Whoops, thanks for catching this! Just removed the comment.

2020-09-25 22:46 UTC, fedarko commented on empress/_plot.py
> +    shear_to_table: bool = True
Makes sense. How does `shear_tree` sound? It's easier to write, and it's consistent with the tree input being `--i-tree`.

2020-09-25 22:58 UTC, ElDeveloper commented on empress/_plot.py
> +    shear_to_table: bool = True
That sounds even better!

2020-09-25 23:16 UTC, fedarko commented on empress/_plot.py
> +    shear_to_table: bool = True
Sounds good -- just renamed the parameter.

2020-09-25 23:17 UTC, fedarko commented
Thanks for the review @ElDeveloper! Suggestions all applied, including hiding the `Export Legend as SVG` button when no metadata is present (thanks for catching that).

2020-09-25 23:48 UTC, ElDeveloper commented
Wonderful, thanks @fedarko!

2020-09-25 23:48 UTC, merged