Tree statistics
biocore/empress pull request #398
Opened 2020-09-29 03:26 UTC by fedarko

Closes #179: adds a "Tree Statistics" tab to the side panel showing the min/max/average node length, as well as node counts (tips, internal nodes, total) for the tree. Also shows node lengths in the selected node menu. (The root node's length is not shown, and is omitted from the node length calculations.) To avoid confusion, renamed "Tree Properties" to "Settings".

Also closes #374 (the root node's x1, x2, y1, and y2 in the unrooted layout are all set to 0, regardless of if the root node actually had a length in the input file).

One notable change here is that the BPTree's lengths are now stored as a regular Array, rather than a Float32Array. I noticed that the lengths stored in the application were inaccurate at relatively low precision (e.g. around ~10^-10), and I'd expect normal JS Numbers to have [more precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64). Switching to use a regular Array seemed to fix the problem.

Another thing worth noting is that now some parts of the UI say "branch length" (e.g. `Ignore branch lengths?` and some say "node length". Not sure which people prefer; can make things consistent if desired.

![stats](https://user-images.githubusercontent.com/4177727/94508873-d0e94400-01c7-11eb-8910-8c3fe46447c5.gif)

2020-09-29 03:36 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F398%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F398%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F398%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F398%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F398%2Fplain.qzv)

2020-09-29 22:24 UTC, ElDeveloper requested changes
Looks great, just a couple of small requests.

2020-09-29 23:19 UTC, fedarko commented on empress/support_files/js/side-panel-handler.js
> +        document.getElementById("stats-avg-length").textContent = stats.avg;
Sure, no problem. Do you think we should also format node lengths in the selection menu to a fixed number of decimal places? (If so, I think it might make sense to keep the precision there higher, e.g. 10ish decimal places.)

2020-09-30 00:06 UTC, ElDeveloper commented on empress/support_files/js/side-panel-handler.js
> +        document.getElementById("stats-avg-length").textContent = stats.avg;
Those might be fine to leave as is.

2020-09-30 00:16 UTC, fedarko commented on empress/support_files/js/side-panel-handler.js
> +        document.getElementById("stats-avg-length").textContent = stats.avg;
Got it. OK, should be addressed now.

2020-09-30 00:27 UTC, fedarko commented on empress/support_files/js/side-panel-handler.js
> +        this.populateTreeStats();
Yep -- just set this up. The actual computation is triggered in `empress-template.html`, in the same location that defines the side panel tab collapsing behavior.

2020-09-30 00:48 UTC, ElDeveloper commented
Wonderful, thanks so much @fedarko!

2020-09-30 00:48 UTC, merged