NEW Add reverse argument for Colorer
biocore/empress pull request #423
Opened 2020-10-14 22:30 UTC by gwarmstrong

#418 

This PR adds functionality to Colorer to support reversing color maps. I have also integrated the reverse with the feature metadata coloring UI element.

You can see the feature in action [here](https://drive.google.com/file/d/1rGFY7TVp4eM9XoPmtvsXszomlkbFZfto/view?usp=sharing).

Notes/questions:

Custom color maps are not supported (my understanding is that the user supplies an object that performs the mapping, which is unordered, so cannot be “reversed”)

Are there other places where you would like me to implement the UI elements for reversing the color map?

Tests:

[x] Colorer with reverse=true works with discrete color map

[x] Colorer with reverse=true works with continuous color map

[x] Colorer with reverse=true works with ordinal color map

[x] Emperor.colorByFeatureMetadata switches the color values when reverse=true

2020-10-14 22:40 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F423%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F423%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F423%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F423%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F423%2Fplain.qzv)

2020-10-14 23:42 UTC, fedarko commented
This looks sweet! Haven't dug through the changes very thoroughly yet, but will try to get that done this week. Looks like things are really well-tested, so thanks for that :)

> Are there other places where you would like me to implement the UI elements for reversing the color map?

I guess this functionality would be useful pretty much everywhere in Empress that assigns colors, right? I think this would be most useful right now for continuous color maps (currently these are only used for feature metadata barplots, but soon they'll be used for other stuff -- #405, #353, ...). Past that, the other places in Empress that assign colors I can think of are:

  - Sample metadata coloring
  - Feature metadata barplots
  - Sample metadata barplots
  - Animations

There is one question I'd like to ask -- not sure what your thoughts on this are. When reversing a categorical (or discrete idk) color map for _N_ categories, there are two options I can think of:

1. Take the first _N_ colors from the color map and then reverse them (this is what this PR currently does)
2. Take the last _N_ colors from the color map (starting with the last color in the map, and then working backwards)

Option 2 seems like it would be more intuitive to me. One reason is that the current way this works means that the start color changes depending on how many categories there are, which could be confusing:

![rev](https://user-images.githubusercontent.com/4177727/96056043-76441f00-0e3a-11eb-9d09-121e53f30c4f.gif)

...  whereas starting from the "end" of the color map (for `Classic QIIME Colors`, this is that weird shade of turquoise) means that the first color is consistently turquoise. Another benefit is that this might simplify some of the discrete color assignment code -- since we'd be able to just reverse the `palette` array and handle everything the same way from then on, I think.

Do you have a preference on how to handle this? I guess we could implement both and make "Reversing method" or something another option, but having an option for an option might be veering into "too much stuff" territory.

Thanks so much!!! :art:

2020-10-14 23:55 UTC, kwcantrell commented
Thanks @gwarmstrong this is a much needed feature!

I agree with @fedarko, reversing the colors would be nice to have for pretty much all coloring options (or at least barplots).

2020-10-15 18:12 UTC, gwarmstrong commented on tests/test-empress.js
> +                "color 1 is second last qiime color"
```suggestion
                "color 2 is second last qiime color"
```

2020-10-15 23:09 UTC, gwarmstrong commented
The build is green and I hooked up the color reversing to sample metadata, feature metadata barplots, sample metadata barplots, and animations! Should be ready for a review.

2020-10-16 00:56 UTC, fedarko requested changes
A couple small things, but this looks really nice! Thanks so much for putting this together.

2020-10-16 00:56 UTC, fedarko commented on empress/support_files/js/colorer.js
> +            palette = [...palette];
I'm guessing this line is designed to convert the palette into a JS array so `.reverse()` can be used. If so, I think it might be nice to restate this [using underscore.js](https://underscorejs.org/#toArray) as

```suggestion
            palette = _.toArray(palette);
```

I doubt that this will make a difference efficiency-wise, but I think it should be more clear to readers.

2020-10-16 00:56 UTC, fedarko commented on empress/support_files/js/colorer.js
>              // the "first" color in the color map, the last value gets the
(comment applies to the `if` block above this -- GitHub won't let me comment there)

For consistency's sake, I think it might make sense to assign the "last" color in the color map to single-unique-value inputs. So e.g. if `Pink-Yellow-Green` is selected as the color scheme and the reverse option is used, then Green should be the first color used in the legend, regardless of how many unique values there are.

2020-10-16 00:56 UTC, fedarko commented on empress/support_files/js/empress.js
> +    Empress.prototype.colorBySampleCat = function (cat, color, reverse = true) {
I think the default for `reverse` should be false here, right? Judging by the application behavior and what the docs comment says.

2020-10-16 00:56 UTC, fedarko commented on tests/test-barplots.js
> +        equal(layer1.colorByFMColorReverse, false);
(QUnit's syntax is kinda funky, but the surrounding tests use `notOk()` and `ok()` to assert false/true respectively so this should probs be consistent.)

```suggestion
        notOk(layer1.colorByFMColorReverse);
```

2020-10-16 00:56 UTC, fedarko commented on tests/test-barplots.js
> +        equal(layer1.colorBySMColorReverse, false);
```suggestion
        notOk(layer1.colorBySMColorReverse);
```

2020-10-16 00:56 UTC, fedarko commented on tests/test-colorer.js
> +            // CVALDISCRETETEST
```suggestion
```
(the other use of this comment in this file was [to help with searching for a specific test](https://github.com/biocore/empress/blob/a76ebf27a8c3730c60a8c5721aa899f2d3ff2e13/empress/support_files/js/empress.js#L1578-L1584); doesn't apply here i think)

2020-10-16 00:56 UTC, fedarko commented on tests/test-colorer.js
> +            // the colors in the previous test
Could you restore the old comment here? The resulting color assignments for these tests shouldn't be just reversed (aside from the extreme values), since one of them has `useQuantScale` set to true while the new one has that set to false.

2020-10-16 00:56 UTC, fedarko commented on tests/test-empress.js
> +            let cm_copy = cm;
```suggestion
```

doesn't look like this variable is used anywhere

2020-10-19 16:09 UTC, gwarmstrong commented on empress/support_files/js/empress.js
> +    Empress.prototype.colorBySampleCat = function (cat, color, reverse = true) {
```suggestion
    Empress.prototype.colorBySampleCat = function (cat, color, reverse = false) {
```

2020-10-19 16:10 UTC, gwarmstrong commented on empress/support_files/js/empress.js
> +    Empress.prototype.colorBySampleCat = function (cat, color, reverse = true) {
Good catch.

2020-10-19 16:12 UTC, gwarmstrong commented on tests/test-colorer.js
> +            // the colors in the previous test
Sorry, probably was not editing the right comment, careless on my end...

2020-10-19 16:13 UTC, gwarmstrong commented on tests/test-colorer.js
> +            // the colors in the previous test
```suggestion
            // Expected colors determined by trying
            // chroma.scale("PiYG").domain([-5,5])(n); where n = 0, 1, 2, etc.
            // (see the interactive docs at https://gka.github.io/chroma.js/ --
            // super useful for testing this)
```

2020-10-19 16:14 UTC, gwarmstrong commented on tests/test-empress.js
> +            let cm_copy = cm;
Yeah carry-over from developing the test, my bad.

2020-10-19 18:01 UTC, fedarko commented on empress/support_files/js/colorer.js
> +            palette = [...palette];
That makes sense, thanks for clarifying your intent! I think your understanding is correct; JS is a bit funky but Objects (including Arrays) are passed by reference, so it'd be possible for the `reverse` to impact the palette. Thanks for being so cautious about this.

Ok, in this case (sorry to ask for another change here) my previous suggestion was suboptimal -- I don't think `_.toArray()` makes the most sense for creating a copy, at least from the perspective of readability. Would it be possible to just replace `_.toArray()` with `_.clone()`? This way it is as clear as possible to readers _why_ this step is being taken. Alternately, I also wouldn't mind going back to the `...` syntax instead, provided we add a comment just linking to this thread or whatever (basically just explaining that this is a necessary step, in the hopes that one of us doesn't come back to this 10 years from now and go "hmm that line probably wasn't doing anything important anyway" ;).

![image](https://user-images.githubusercontent.com/4177727/96493704-29759500-11fa-11eb-8948-e1c5dc9fb831.png)

2020-10-19 18:03 UTC, fedarko commented on tests/test-colorer.js
> +            // the colors in the previous test
No worries!

2020-10-19 18:06 UTC, gwarmstrong commented on empress/support_files/js/colorer.js
> +            palette = _.toArray(palette);
```suggestion
            palette = _.clone(palette);
```

2020-10-19 18:07 UTC, gwarmstrong commented on empress/support_files/js/colorer.js
> +            palette = [...palette];
Yeah the `_.toArray -> _.clone` change makes sense.

2020-10-19 20:13 UTC, fedarko requested changes
just a quick fix, but everything looks good! Once this is in I think this is ready to merge.

2020-10-19 20:13 UTC, fedarko commented on tests/test-colorer.js
> +            equal(colorer.__valueToColor.abc, "#fee825");
```suggestion
            // The last value in the color map (for viridis, yellow)
            // should be used.
            equal(colorer.__valueToColor.abc, "#fee825");
```

2020-10-19 20:46 UTC, merged

2020-10-19 20:47 UTC, fedarko commented
Thanks @gwarmstrong! :art:

2020-10-26 16:47 UTC, ElDeveloper commented
Thanks @gwarmstrong! And thanks for reviewing @kwcantrell @fedarko! 🎉