Fix clicking on nodes not in table; refactor and test node selection menu; fix "Add" button
biocore/empress pull request #432
Opened 2020-10-23 00:46 UTC by fedarko

Closes #314. Now, clicking on a tip not in the table shows text to the user explaining the situation:

![image](https://user-images.githubusercontent.com/4177727/96942454-095c0500-148a-11eb-856f-7f9fab708722.png)

Similarly, clicking on an internal node where none of its descendant tips are in the table also shows a note:

![image](https://user-images.githubusercontent.com/4177727/96942502-285a9700-148a-11eb-93f6-06ec440a9f18.png)

This also refactors the node selection menu a decent amount. Mainly, I realized while working on #314 that a lot of the showing / hiding operations in the menu rely on some pretty complex logic and were done in a very ad-hoc way (this is primarily my fault lol), so I tried to make things more manageable. Now, more of the work is delegated to `makeFeatureMetadataTable()` / `makeSampleMetadataTable()`, so life should be easier. This PR also adds some tests for the menu -- these are by no means comprehensive, but they should be a good start.

While I was at it, I also fixed #272 and added a test for it.

Last change worth noting, I think, is that I removed `SelectedNodeMenu._checkTips()`. When more than a few tips were not present in the tree, the toast messages shown were kind of hard to read (see below); furthermore, it looks like the tip keys rather than names were being shown, anyway, which makes interpreting these messages hard for users. Since the revamped menu now has the ability to show these sorts of warnings a lot more cleanly, I delegated this to there.

_Before:_
![b42](https://user-images.githubusercontent.com/4177727/96943883-37dbdf00-148e-11eb-92a6-0a5f0e5bcd47.png)

_After:_
![yeeee](https://user-images.githubusercontent.com/4177727/96943811-095e0400-148e-11eb-8ee8-a85e75ff5eda.png)

2020-10-23 00:49 UTC, fedarko commented
... also, for reference for whoever reviews this, here's a flowchart i drew out on all of the cases possible when showing the sample metadata stuff to the user. Turns out user interfaces are really hard!

![jank](https://user-images.githubusercontent.com/4177727/96944110-ca7c7e00-148e-11eb-97d1-e010cb73115b.png)

(note: i might have missed something so this might not actually be comprehensive ._.)

2020-10-23 00:56 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F432%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F432%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F432%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F432%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F432%2Fplain.qzv)

2020-11-10 02:51 UTC, ElDeveloper requested changes
Works great, just a few minor suggestions.

2020-11-10 02:51 UTC, ElDeveloper commented on empress/support_files/js/select-node-menu.js
> +                        "can't show sample presence information for it.";
What about a shorter version:

```suggestion
                        "This tree tip is not " +
                        "present in the input feature table, so we " +
                        "can't show sample presence information for it.";
```

2020-11-10 02:51 UTC, ElDeveloper commented on empress/support_files/js/select-node-menu.js
> +                        "This is an internal node in the tree. None of " +
Same here ... `None of the descendants of this internal node in the tree ...`

2020-11-10 02:51 UTC, ElDeveloper commented on empress/support_files/js/select-node-menu.js
> +            // https://github.com/biocore/empress/issues/337 refactoring.
If this is already documented elsewhere I think it's safe to keep this comment out.

```suggestion
```

2020-11-10 02:51 UTC, ElDeveloper commented on empress/support_files/js/select-node-menu.js
> +         * [x,y,r,g,b,...] where x,y are the coords of the highlighted nodes.
Is this still valid considering the changes that went in last week to update the way colors are stored?

2020-11-10 02:51 UTC, ElDeveloper commented on empress/support_files/css/empress.css
> +/* TODO: remove overlap between top/bottom borders? */
Yeah that would probably be nice, the borders look a bit funny IMHO. I would suggest removing them altogether `¯\_(ツ)_/¯`

2020-11-10 21:01 UTC, fedarko commented on empress/support_files/js/select-node-menu.js
> +         * [x,y,r,g,b,...] where x,y are the coords of the highlighted nodes.
Oof, no it is not! Thanks for pointing this out. I'll update the comment.

2020-11-10 21:18 UTC, fedarko commented on empress/support_files/css/empress.css
> +/* TODO: remove overlap between top/bottom borders? */
I kinda like the borders, just because it makes it clear which UI elements apply to the feature metadata stuff vs. which apply to the sample metadata stuff (the distinction isn't always clear IMO without the borders, e.g. the sample metadata summarize elements). I'll try to fix the adjacent border stuff and hopefully that makes it look nicer ;P

2020-11-11 00:06 UTC, fedarko commented on empress/support_files/css/empress.css
> +/* TODO: remove overlap between top/bottom borders? */
Actually, I spent longer than I'd like to admit trying to make the borders look the way I wanted them to and was not very successful. So... yeah, I went ahead and removed the borders :man_shrugging: 

I did change up a few things to still make the "groupings" of UI elements clear. Here's what things look like now:

Both feature and sample metadata available:
![image](https://user-images.githubusercontent.com/4177727/98748197-090aa780-236e-11eb-9e55-14941e688c1f.png)

Just feature metadata available:
![image](https://user-images.githubusercontent.com/4177727/98748279-2b9cc080-236e-11eb-9c05-539191f4acbb.png)

Just sample metadata available:
![image](https://user-images.githubusercontent.com/4177727/98748289-33f4fb80-236e-11eb-8aff-8d5f56181b56.png)

I think this ended up looking better than it did before, so thanks for the suggestion ;)

2020-11-11 00:09 UTC, fedarko commented on empress/support_files/js/select-node-menu.js
> +                        "can't show sample presence information for it.";
The reason I kept things like this was to be consistent with the other "notes" text that's shown in the alternative case (when this node is in the table) in Empress, [here](https://github.com/biocore/empress/blob/e982e65b5983299cddbf3665472bfd7d5cca254f/empress/support_files/js/select-node-menu.js#L283-L287) and [here](https://github.com/biocore/empress/blob/e982e65b5983299cddbf3665472bfd7d5cca254f/empress/support_files/js/select-node-menu.js#L389-L394).

I'd be down to change this in the future (maybe adding another UI element next to `Node length:` at the top of the menu that has something like `Node type:` and then `tip` or `internal`), but I would prefer to keep this as is for now. (I don't feel _super_ strongly about this, tho, so if you'd prefer we can change this up now :)

2020-11-11 00:10 UTC, fedarko commented
Thanks @ElDeveloper! Changes should be ready for a second pass.

2020-11-11 00:14 UTC, ElDeveloper commented on empress/support_files/css/empress.css
> +/* TODO: remove overlap between top/bottom borders? */
That looks super slick! ✨ 

Thanks so much for looking into this!

2020-11-16 22:08 UTC, ElDeveloper approved these changes

2020-11-16 22:09 UTC, merged

2020-11-16 22:27 UTC, fedarko commented
Thanks @ElDeveloper!

2020-11-16 22:29 UTC, ElDeveloper commented
Thanks @fedarko!

On (Nov-16-20|14:28), Marcus Fedarko wrote:
>Thanks @ElDeveloper!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://urldefense.com/v3/__https://github.com/biocore/empress/pull/432*issuecomment-728368031__;Iw!!Mih3wA!Q4muwYw6kYl56xWU5LsgErObDmHyDIYOhFSdVh0vJj0RSm3MP390VO9gSUSHhfU$