Fix 364
biocore/empress pull request #433
Opened 2020-10-26 22:53 UTC by kwcantrell

Resolves #364. This implements a binary search and also limits the number of suggestions to 10 ids

Here is a link to the improved [version](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2F7xrpr6z8vzoot24%2Ffast_autofill.qzv%3Fdl%3D1) and here is a link to the original [version](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2F9ybj0aqtj0nhajz%2Fslow_autofill.qzv%3Fdl%3D1).

You can test them by searching for 'taag' in the node search box.

2020-10-26 23:37 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F433%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F433%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F433%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F433%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F433%2Fplain.qzv)

2020-11-07 02:24 UTC, fedarko requested changes
Thanks @kwcantrell! Some suggestions -- main thing is that it looks like the functionality added is still commented out, and should be re-enabled. Also, I think the null-filtering should probably be re-enabled, as well.

2020-11-07 02:24 UTC, fedarko commented on empress/support_files/js/canvas-events.js
> +                            query.toUpperCase()
It looks like this check is duplicated just below this in `canvas-events.js`. Would you mind refactoring it into a helper function, just so we only need to update this once in the future if needed?

2020-11-07 02:24 UTC, fedarko commented on empress/support_files/js/canvas-events.js
> +                        );
... Also, this PR isn't really the place to ask about it, but just to check -- the case insensitivity only applies to suggestions, right? It should be possible for two nodes with differently-cased names (e.g. `"abc"` and `"AbC"`) to be present in the same tree, and each should be searchable individually. I think this is already the case, but just wanted to verify (if there are problems we can open a new issue for fixing that).

2020-11-07 02:24 UTC, fedarko commented on empress/support_files/js/canvas-events.js
> +                // }
Should this be un-commented? (If not, we should probably remove it.)

2020-11-10 16:43 UTC, kwcantrell commented on empress/support_files/js/canvas-events.js
> +                        );
Correct, case insensitivity is only used in the suggestions menu to make comparisons easier. In you above example if the user typed `"a"` in the search menu then both `"abc"` and `"AbC" would be suggested to the user. However, case insensitivity is not used when searching for a specific node. For example if the user typed `"abc"` in the search menu and then either clicked on the search button or pressed the enter key, only node `"abc"` would be shown on the empress tree.

2020-11-11 00:17 UTC, fedarko commented on empress/support_files/js/canvas-events.js
> +                        );
Awesome, thanks for clarifying! Good to know.

2020-11-17 02:22 UTC, kwcantrell commented on empress/support_files/js/empress.js
>          nodeNames.sort();
The goal was to cut back the number of computational cycles. But I agree, filtering the nulls is a one time cost and its worth doing to avoid any potential errors.

2020-11-17 05:48 UTC, fedarko commented
Thanks so much @kwcantrell! Going through the updates now :)

@antgonza Quick question -- is it possible to send a "kick"/trigger message to McHelper? Going by the provenance / functionality it looks like the QZVs for this PR haven't been updated in response to the recent commits to this branch, which is making manual testing a bit more cumbersome here.

![funky](https://user-images.githubusercontent.com/4177727/99351430-6b274900-2855-11eb-84fa-96a143d6dff4.png)

2020-11-17 06:27 UTC, fedarko requested changes
A few suggestions (mostly documentation but one functionality thing). Thanks so much, this is looking awesome!

2020-11-17 06:27 UTC, fedarko commented on empress/support_files/js/canvas-events.js
> +            if (suggestionsAdded < ids.length) {
It looks like the `...` shows up even if there is only one value shown in the menu -- I think this is because there is only one possible "option" here, i.e. the `0.000` name, so `suggestionsAdded` for the query `0.000` is immediately less than `ids.length`. I thought at first that this might be a result of the unique-filtering code you added, but from going through the code I don't think that's the reason.

I think (?) there should instead be some logic that distinguishes between when we already have 10 suggestions added and we had to cut things off (in which case we should show the `...`), and the other cases (e.g. the query is so specific that 10 or fewer items are shown, in which case we should not show the `...`)

![uniqs_huh](https://user-images.githubusercontent.com/4177727/99353493-7aa89100-2859-11eb-9ef4-cd3516240681.gif)

2020-11-17 06:27 UTC, fedarko commented on empress/support_files/js/empress.js
>          nodeNames.sort();
Thanks -- yeah, if this gets to be a bottleneck we can definitely speed things up somehow, e.g. maybe adding a special `BPTree.getAllNonNullNodeNames()` or something like that. But for now I think this should be fine.

Filtering to unique node names makes sense, I like that this cleans things up in the menu :D

2020-11-17 13:43 UTC, antgonza commented
@fedarko, my guess is that `d9f6850` and `056f93b` happened too quickly; @kwcantrell, could you do one push with some minimal changes to see if things work fine?

2020-11-17 17:43 UTC, fedarko commented on empress/support_files/js/empress.js
>          nodeNames.sort();
https://stackoverflow.com/a/9645447/10730311

2020-11-17 21:32 UTC, fedarko reviewed
Some tiny comments, but this is pretty much fine as is. Thanks so much @kwcantrell!

2020-11-17 21:32 UTC, fedarko commented on empress/support_files/js/empress.js
> +        console.log(nodeNames);
Could you remove the console.log here?

Also -- do you think it might make sense to move some of this code to a new utility function that just takes a list of node names and filters nulls, sorts it case-insensitively, and filters it to unique stuff? This way, it'd be a lot easier to test this functionality directly. (I mean it works now, so it's not a big issue or anything, but it would probs make the code a bit cleaner.) Not something we have to do in this PR, necessarily.

2020-11-17 21:32 UTC, fedarko commented on empress/support_files/js/empress.js
> +        });
Cool! No idea this existed, this seems like a good way of handling this.

2020-11-17 21:32 UTC, fedarko commented on empress/support_files/js/empress.js
> +        nodeNames.sort(function (a, b) {
```suggestion
        // Sort node names case insensitively
        nodeNames.sort(function (a, b) {
```

2020-11-20 05:41 UTC, merged