[WIP] Add standalone CLI options
biocore/empress pull request #449
Opened 2020-11-17 19:53 UTC by gibsramen

Closes #425 

Adds two scripts `empress tree-plot` and `empress community-plot`

## Important changes:

- Added a `q2` flag to `_plot_utils.save_viz` indicating whether to save with the QIIME2 specific stuff (defaults to True so nothing should change in existing tests).
- Moved some of the PCoA processing from `_plot.community_plot` to a new method `_plot_utils.prepare_pcoa`. This allows us to reuse this code for the standalone community plotting.

## Current status:

- [x] Scripts added
- [ ] Documentation updated
- [ ] Parameter descriptions (i.e. `--help`)
- [ ] CLI tests

2020-11-17 21:11 UTC, fedarko reviewed
This looks so cool. Have one quick comment I noticed from reading over things (I get that this is a WIP so no worries, just figured i'd bring it up sooner rather than later)

2020-11-19 02:33 UTC, gibsramen commented
Ready for review! I talked with @fedarko a bit about how we should approach unit testing the standalone version of `tree-plot` and `community-plot`. Currently there are 4 unit tests:

1. Test that `empress tree-plot`
2. Test that `empress community-plot` without PCoA
3. Test that `empress community-plot` with PCoA
4. Test that the standalone properly handles the case where the output directory already exists

The first 3 tests check that the commands return a passing exit code and that the relevant directories/files exist. We felt it would be unwieldy/redundant to check the contents of the visualizations. If folks think that this should be included I'm happy to take suggestions about how to implement this.

2020-11-20 21:00 UTC, fedarko requested changes
This looks so dope. Thanks a ton for working on this! It's going to be super helpful.

2020-11-24 20:31 UTC, gibsramen commented on README.md
> +If you are not using QIIME 2, feel free to skip to the next section.
Cool - so maybe for the scope of this PR I can move the standalone example (and make the other requested changes). So then, if I'm understanding your comment correctly, the format of the README would look like this:

* Introduction
* QIIME2
    * Installation
    * Basic usage
* Standalone
    * Installation
    * Basic usage
* Comprehensive Q2 tutorial
* Pub, citation, acknowledgements

Then we can open up a new issue/discuss moving the current tutorial elsewhere. Is that in-line with what you were thinking?

2020-11-24 22:12 UTC, fedarko commented on README.md
> +If you are not using QIIME 2, feel free to skip to the next section.
Yeah, that matches what I was thinking of. I would request we move the standalone section to above the QIIME 2 section, but aside from that this order of things sounds perfect 💯

2020-12-05 00:41 UTC, fedarko reviewed
Code looks great -- all that's left are some fiddly little documentation things, mostly targeted at new users. This looks fantastic, thank you so much!

2020-12-05 00:41 UTC, fedarko commented on README.md
> +Empress is available as either a standalone program or a QIIME 2 plugin. The standalone version will generate a folder with HTML/JS/CSS files necessary to view the plot while the QIIME 2 version will
```suggestion
Empress is available as either a standalone program or a QIIME 2 plugin. The standalone version will generate a folder with HTML/JS/CSS files necessary to view the plot, while the QIIME 2 version will generate a `.qzv` Visualization that can be viewed on [https://view.qiime2.org/](https://view.qiime2.org/) or by using `qiime tools view`.
```

2020-12-05 00:41 UTC, fedarko commented on README.md
> +The standalone version of Empress takes the following filetypes as inputs.
```suggestion
The standalone version of Empress takes the following filetypes as inputs. (Note that for `empress tree-plot` all of these except for the tree are optional, and for `empress community-plot` all except for the tree, feature table, and sample metadata are optional.)
```

2020-12-05 00:41 UTC, fedarko commented on README.md
> +
```suggestion
### Available commands

Empress provides two commands: `empress tree-plot` and `empress community-plot`. Both commands generate an Empress visualization, but `community-plot` requires you to pass in a feature table and sample metadata while `tree-plot` only requires a tree file. See [this section](#first-a-note-about-empress-commands) of the docs for some more details.
```

feel free to adjust this as you see fit -- just trying to be clear about this

2020-12-05 00:41 UTC, fedarko commented on README.md
> +# Tutorial: Using Empress in QIIME 2
I can't leave a suggestion at the correct line in the GitHub interface, but I would suggest changing the line that says "Empress currently has two commands available through QIIME 2" a little bit further down from here to remove the "through QIIME 2" part. This way we can refer users to this section from the standalone docs.

2020-12-05 00:41 UTC, fedarko commented on README.md
> +You can replace `qiime2-2020.8` above with whichever version of QIIME 2 you have currently installed. Install Empress through PyPi by using `pip install empress`. Once you have installed Empress, run
```suggestion
You can replace `qiime2-2020.8` above with whichever version of QIIME 2 you have currently installed.

Now, run the following command to install Empress using PyPI:

`pip install empress`

Once you have installed Empress, run the following commands to ensure that Empress was installed correctly. If you see information about Empress' QIIME 2 plugin, the installation was successful!
```

This is really just adding a few line breaks to emphasize the `pip install empress`, so that impatient people like me don't skim through this and go "wait hold up why is QIIME saying that Empress isn't installed" ._.

2020-12-05 00:41 UTC, fedarko commented on README.md
> +### Example QIIME 2 usage
```suggestion
### Available commands
Empress' QIIME 2 plugin provides two commands: `qiime empress tree-plot` and `qiime empress community-plot`. Both commands generate an Empress visualization, but `community-plot` requires you to pass in a feature table and sample metadata while `tree-plot` only requires a tree file. See [this section](#first-a-note-about-empress-commands) of the docs for some more details.

### Example QIIME 2 usage
```

I know this duplicates some of the text that I suggested above, but I can't think of a better way to do this, sorry ._. Feel free to push back on this -- if desired we could not bother with this change for right now. The main goal in adding this text is just preventing people from skimming, going "oh huh you need all those files for this??? i'm just gonna use another tool instead," and then ignoring empress for the rest of their lives :P

2020-12-05 00:41 UTC, fedarko commented on README.md
> +### Example QIIME 2 usage
Actually thinking about it, I guess alternately maybe we could just add two commands for each `Example usage` section? (one showing tree plot, one showing community plot). That would also work -- I'll leave the decision up to you.

2020-12-05 00:41 UTC, fedarko commented on README.md
> +### Example standalone usage
```suggestion
### Input files
```

2020-12-05 00:41 UTC, fedarko commented on README.md
> +empress community-plot \
This looks great. Could you add in a `tree-plot` example above this? Alternately, or some brief documentation that there are two commands available, to avoid users getting overwhelmed

2020-12-05 00:41 UTC, fedarko commented on empress/_plot_utils.py
> +
```suggestion
```

2020-12-05 00:41 UTC, fedarko commented on empress/_plot_utils.py
> +
(just making there be only 1 blank line here)

2020-12-08 01:17 UTC, fedarko approved these changes
Looks good to me. thanks so much!

2020-12-08 01:17 UTC, fedarko commented on README.md
> +You can view the details of the command line arguments with `empress tree-plot --help` and `empress community-plot --help`. Note that the path provided to `--output-dir` must not exist as it will be
```suggestion
You can view the details of the command line arguments with `empress tree-plot --help` and `empress community-plot --help`. Note that the path provided to `--output-dir` must not exist as it will be created by Empress upon successful execution of the command. It is also worth noting that the standalone version of the Empress commands does not support providing multiple sample/feature metadata files. If you have, for example, multiple feature metadata files, you should combine them all into one file that you pass to Empress.
```

2020-12-08 01:17 UTC, fedarko commented on README.md
> +Try running the command `empress --help` to ensure that Empress has been installed properly. If you see details for the different Empress commands then the installation has succeeded and you are read
```suggestion
Try running the command `empress --help` to ensure that Empress has been installed properly. If you see details for the different Empress commands then the installation has succeeded and you are ready to start using Empress!
```

2020-12-16 19:22 UTC, fedarko commented
Now that the CI is up and running (:D), is it ok if I merge this in?

2020-12-16 19:33 UTC, ElDeveloper commented
Sounds great to me!

On (Dec-16-20|11:23), Marcus Fedarko wrote:
>Now that the CI is up and running (:D), is it ok if I merge this in?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://urldefense.com/v3/__https://github.com/biocore/empress/pull/449*issuecomment-746871067__;Iw!!Mih3wA!QqkoB5YZKSpySV5wbrfY2cPPt8MI2uMvBsAhSjo6GWl12EvP-ZpOIGFzhS3PiqU$

2020-12-16 19:35 UTC, merged

2020-12-16 19:37 UTC, fedarko commented
Thanks so much @gibsramen!!! :black_large_square: :straight_ruler:

2020-12-16 19:43 UTC, ElDeveloper commented
Thanks @gibsramen and @fedarko!

On (Dec-16-20|11:37), Marcus Fedarko wrote:
>Thanks so much @gibsramen!!! :black_large_square: :straight_ruler:
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://urldefense.com/v3/__https://github.com/biocore/empress/pull/449*issuecomment-746893873__;Iw!!Mih3wA!RZYjhgp6H1ODlZ7qFCoTGf43CeLq_-9thUbsC9nZC4sbmcA6HynkjZ0GLBHCUpA$