NEW warn when layout options (approximately) do not change branch lengths
biocore/empress pull request #456
Opened 2020-11-25 19:19 UTC by gwarmstrong

Fixes #447 .

This PR follows up on #444 to raise a toast message if the tree is not changed by options like "make ultrametric" and "ignore branch lengths".

When working on a tree from qemistree (thanks @gibsramen ), I found that the branch lengths could be modified by small amounts by the make ultrametric code, but this resulted in no visible difference between the two trees. As a result, I introduced a tolerance for how similar branch lengths should be in order to make this warning. Though this could result in a warning being falsely raised in the case where the branch lengths in the tree are all very small.

![Screen Shot 2020-11-25 at 11 05 42 AM](https://user-images.githubusercontent.com/19470970/100271354-3890e680-2f0e-11eb-8145-abe1891cae6d.png)

2020-11-30 21:03 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +            // anyDifferent = anyDifferent || nodeLen !== tree.length(prepos);
```suggestion
```

2020-11-30 21:03 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +            // anyDifferent = anyDifferent || nodeLen !== tree.length(n);
```suggestion
```

2020-12-01 19:20 UTC, kwcantrell reviewed
Thanks @gwarmstrong! This looks good. I just have a couple minor comments.

2020-12-01 19:20 UTC, kwcantrell commented on empress/support_files/js/layouts-util.js
> +    function shouldCheckBranchLengthsChanged(methodName) {
this looks like it returns a boolean?

2020-12-01 19:20 UTC, kwcantrell commented on empress/support_files/js/layouts-util.js
> +                anyDifferent || Math.abs(nodeLen - tree.length(prepos)) > TOL;
perhaps instead of using an absolute number for the tolerance, we can use a percentage changed? Using a percentage changed instead of an absolute number would "normalize" the tolerance across all branch lengths.

2020-12-01 19:20 UTC, kwcantrell commented on empress/support_files/js/layouts-util.js
> +            util.toastMsg(NO_LENGTHS_CHANGED_MSG, NO_LENGTHS_CHANGED_DURATION);
might want to make this a helper function since it this same block is used in multiple functions.

2021-01-04 17:47 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +    function shouldCheckBranchLengthsChanged(methodName) {
Fixed here https://github.com/biocore/empress/pull/456/commits/1e86bc9b7372f505a04c7dd653dbd3e40b8779ba

2021-01-04 17:48 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +                anyDifferent || Math.abs(nodeLen - tree.length(prepos)) > TOL;
Good idea. Fixed here: https://github.com/biocore/empress/pull/456/commits/22f12fe1920e6d4afb5702399b47d1de0edbbe20

2021-01-04 17:48 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +            util.toastMsg(NO_LENGTHS_CHANGED_MSG, NO_LENGTHS_CHANGED_DURATION);
Changed here: https://github.com/biocore/empress/pull/456/commits/77c03da0e439f7282914719c81b5dd08cadd6c25

2021-01-26 00:40 UTC, fedarko requested changes
I have a few small changes that I think would be useful, but none of them are very large. Thank you for getting this ready, and let me know if I can help out with anything!

2021-01-26 00:40 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +                Math.abs(tree.length(prepos) / nodeLen - 1) > TOL;
I have three suggestions:

1. It's not going to make a difference except (maaaybe) for huge trees, but division is kind of expensive. It seems to me like the final line here could be rewritten simpler as
   
   ```js
   Math.abs(tree.length(prepos) - nodeLen) > TOL;
   ```
   This should be more efficient and easier to read (unless I'm missing something).

2. If `checkLengthsChange` is false, then we don't need to bother with updating `anyDifferent` at all. Therefore, I suggest that we wrap the `anyDifferent = ` statement inside an `if (checkLengthsChange)` branch, so that we don't spend time updating this unless it's necessary.

3. Even if `checkLengthsChange` is true, then we can stop trying to update `anyDifferent` as soon as we find one case where the length is different (i.e. as soon as we set `anyDifferent` to true). Therefore, I suggest that we modify the aforementioned if statement to be something like `if (checkLengthsChange && !anyDifferent)`.

Does this all make sense? Let me know if I missed something.

2021-01-26 00:40 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +            noLengthsChangedMsg();
In order to limit code reuse, it might be worth moving the line that updates anyDifferent to a separate function, so that way future modifications to that are just stored in one place.

(...but I get it if you'd prefer to not bother with this for now)

2021-01-26 00:40 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +            ignore: true,
One slight problem with the current approach is that it only works when all the node lengths are 1 - if all the nodes have lengths of 2 or something, then this isn't identified (even though these cases look identical). This is discussed a bit in #447.

...That being said these corner cases are rare and not very important, so I'm cool with not worrying about this.

2021-01-26 00:40 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +        "No branch lengths modified by layout options.";
```suggestion
        "It doesn't look like any branch lengths were changed by the current method of modifying branch lengths.";
```

Rationale for this:

1. Gives us leeway, indicating that these messages aren't perfect (both due to tolerance things and due to missing the ignore lengths stuff i mentioned above)

2. By saying "the current method", we avoid confusing the user -- these toast messages show up every time the user changes the layout while an "alternate branch length method" (eg ultrametric) is selected, so wording things this way makes it clearer that the actual layout algorithm isn't the reason for these messages.

2021-01-26 00:40 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +        "No branch lengths modified by layout options.";
(the styling code will probably want this string to be broken onto two separate lines, sorry if it yells at you)

2021-01-27 00:00 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +        "No branch lengths modified by layout options.";
```suggestion
        "It doesn't look like any branch lengths were changed " +
        "by the current method of modifying branch lengths.";
```

2021-01-27 00:41 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +                Math.abs(tree.length(prepos) / nodeLen - 1) > TOL;
What evidence do you have for division being expensive in js?
I found these benchmarks https://www.akselipalen.com/2021/01/13/benchmark-of-elementary-mathematical-operations-in-node-js/
and ran them locally and got results similar to the author's.

The way you wrote the line is what I had originally, but see the comment in my initial post and @kwcantrell 's [follow-up](https://github.com/biocore/empress/pull/456#discussion_r533660491) regarding the insufficiency of absolute tolerance (maximum difference). The relative tolerance (i.e., compare difference of the division between branch lengths) proposed by Kalen solves the problem where, e.g., "make ultrametric" makes a large relative change to small branch lengths. E.g., if all branches in an unbalanced tree of max depth3 are 0.01, and tolerance is 0.1, then "make ultrametric" would change a branch length by at most 0.03, which is less than the tolerance and would trigger the "no changes" warning. But if we do the division, we realize that a branch changing from 0.01 to 0.03 is tripled in length, so we do not want to raise the warning.

Further, I think we can solve the "all branch lengths are 2" problem you [mentioned above](https://github.com/biocore/empress/pull/456/files#r564135982) with the division approach by changing the line to something like

```
                Math.abs(tree.length(prepos) / nodeLen - lengthFactor) > TOL;
```

Where `lengthFactor` is determined by the first call to `tree.length(prepos) / nodeLen`.

2021-01-27 00:41 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +                Math.abs(tree.length(prepos) / nodeLen - 1) > TOL;
Good points on the logic surrounding `checkLengthsChange` and `anyDifferent`!

2021-01-28 00:57 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +            noLengthsChangedMsg();
Updated here: https://github.com/biocore/empress/pull/456/commits/cec5ed6dadaa2df2eb49b60e18a77396cb9fcff3

2021-01-28 00:58 UTC, gwarmstrong commented on empress/support_files/js/layouts-util.js
> +                Math.abs(tree.length(prepos) / nodeLen - 1) > TOL;
Changed the control flow here: https://github.com/biocore/empress/pull/456/commits/000a5b841cbf1c474d6ebaf40c22ff2000561ed1

2021-01-29 02:02 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +                Math.abs(tree.length(prepos) / nodeLen - 1) > TOL;
The point about relative tolerance makes a lot of sense—sorry for missing that discussion.

Re: runtime of arithmetic operations, I was thinking along the lines of https://en.wikipedia.org/wiki/Computational_complexity_of_mathematical_operations. That article is language-independent and JS is high-level enough that I can imagine that division vs. subtraction probably wouldn't make much of a difference, similarly to the benchmarks.

In tandem with the control flow changes, I imagine that prematurely optimizing this is probably not worth the effort right now... So I'm cool with leaving this as is (and if people complain about this being a bottleneck with like trillion-node trees we can cross that bridge when we get to it ;) Thanks for your insight on this!

2021-01-29 02:20 UTC, fedarko requested changes
This is basically fine. I have one suggested change to the any-different-updating function (not passing any different, which simplifies things a bit), and we may want to change the checking back from subtraction to division... but not a huge deal either way. Sorry for nitpicking things here. I'm ok with merging this in provided these changes are addressed (either via the suggestions enclosed in this review, or in another way if you'd prefer).

Thanks so much! Sorry for taking a few days to get to this.

2021-01-29 21:58 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +                anyDifferent = isTransformedLenDifferent(nodeLen, tree, n);
```suggestion
                anyDifferent = isTransformedLenDifferent(nodeLen, tree, prepos);
```

Looks like I broke this sorry ._.  tested locally and confirmed this change should fix things with the rectangular layout

2021-01-29 22:41 UTC, fedarko commented on empress/support_files/js/layouts-util.js
> +                anyDifferent = isTransformedLenDifferent(nodeLen, tree, n);
Committing change due to discussion with @gwarmstrong

2021-01-29 22:42 UTC, merged