New color map
biocore/empress pull request #483
Opened 2021-02-10 05:22 UTC by kwcantrell

This PR adds a new custom diverging color map (green to light orange to purple) that is great for coloring tree branches as a lot of the other diverging color maps are either hard to see the separation of values and/or the middle values are colored to light which makes the branches hard to see. 
![log_ratio](https://user-images.githubusercontent.com/28127694/107468034-1c1f4600-6b1c-11eb-9c7c-695f33644887.png)
You can see that this color map does a good job separating the two extreme values (i.e. endpoints) from the middle values while still making everything visible on screen.

2021-02-10 09:35 UTC, fedarko requested changes
This looks dope! A few small finicky changes I think would improve clarity, but this should be good to go without much tweaking. Thanks for adding this!

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
> +            name: "Purple-Light Orange-Green",
I think we may want to reverse the name of this (calling it `Green-Light Orange-Purple` instead of the other way around). The rationale is that the other Diverging color maps' names go in ascending order (see e.g. `Red-Blue` and `Pink-Yellow-Green` below), whereas the "low" color for this map is purple instead of green.

![image](https://user-images.githubusercontent.com/4177727/107488851-ca3ae800-6b3c-11eb-9229-372fd9b893c8.png)

![image](https://user-images.githubusercontent.com/4177727/107488886-d6bf4080-6b3c-11eb-91a4-9c71d0f09180.png)

![image](https://user-images.githubusercontent.com/4177727/107488912-df177b80-6b3c-11eb-9092-b2d43e37f3b8.png)

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
> +            name: "Purple-Light Orange-Green",
Also, this is much much much less important, but it might make sense to remove the space in between `Light` and `Orange` (so it's just named `Purple-LightOrange-Green` or something) -- currently, none of the other color map names that have hyphens also have a space, so to me the UI looked at first like something went wrong and this was two color maps' names merged together (`Purple-Light` and `Orange-Green` combined into one). But feel free to disagree with this one, I can see how the space helps readability also

![Screenshot_2021-02-10_01-13-11](https://user-images.githubusercontent.com/4177727/107489225-3c133180-6b3d-11eb-9b9f-5ab068b961ae.png)

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
> +    Colorer.__prOrGr = ["green", "#fed8b1", "purple"];
```suggestion
    Colorer.__prOrGr = ["#008000", "#fed8b1", "#800080"];
```
It's probably irrational on my part, but using hex codes just seems somehow "safer" to me -- in case Chroma.js would decide randomly that the default `green` should be another color, or whatever. (I doubt that'd ever happen, but IDK.)

Another motivation for using hex codes instead of color names is that it is consistent with how `Classic QIIME Colors` is declared above -- this could make this color map more portable to other projects that don't use Chroma.js.

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
> +        }
```suggestion
        if (this.color === Colorer.__PR_OR_GR) {
            interpolator = chroma.scale(Colorer.__prOrGr);
        } else {
            interpolator = chroma.scale(this.color);
        }
```

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
> +        }
(Rationale for this: we don't need to set the domain to [0, 1] unless there is just one unique value, so this avoids doing this extra work if we can.)

2021-02-10 09:35 UTC, fedarko commented on empress/support_files/js/colorer.js
>              // If there's only 1 unique value, set its color as the first in
```suggestion
            interpolator = interpolator.domain([0, 1]);
            // If there's only 1 unique value, set its color as the first in
```

Technically I don't even think we need to add this -- the default domain of a scale in chroma is [0, 1] (see [here](https://gka.github.io/chroma.js/#chroma-scale)). However, I do like explicitly setting it as is currently done in this PR, both in case chroma'd change this in the future and to make the code more understandable.

2021-02-22 22:17 UTC, kwcantrell commented on empress/support_files/js/colorer.js
> +            name: "Purple-Light Orange-Green",
That makes sense. I also felt it looked a bit odd with the space but I wasn't sure what the best way to write it. I'll remove the space since the space looks a bit odd in this context.

2021-02-22 22:22 UTC, kwcantrell commented on empress/support_files/js/colorer.js
> +    Colorer.__prOrGr = ["green", "#fed8b1", "purple"];
I'll add the hex codes. I doubt chroma.js would change the default colors but agree that we shouldn't rely on chroma.js to maintain its default colors.

2021-02-22 22:30 UTC, kwcantrell commented on empress/support_files/js/colorer.js
>              // If there's only 1 unique value, set its color as the first in
@fedarko thanks for reviewing this! I think I have addressed all of your comments.

2021-02-22 22:55 UTC, kwcantrell commented
@fedarko thanks for reviewing this! I think I have addressed all of your comments.

2021-02-22 23:09 UTC, fedarko reviewed
Thanks @kwcantrell! This looks great -- I have one suggestion, but we could probably merge this in even without it.

2021-02-22 23:09 UTC, fedarko commented on empress/support_files/js/colorer.js
> +    Colorer.__prOrGr = ["#008000", "#fed8b1", "#800080"];
Would it be possible to change these to reflect the new name? (This'd also involve updating the other uses of these variables throughout this module.)

This is not very high priority, since at this point it's just to avoid confusing future people looking at this code who wonder why the names are switched.

```suggestion
    Colorer.__GN_OR_PR = "GnOrPr";
    Colorer.__gnOrPr = ["#008000", "#fed8b1", "#800080"];
```

2021-02-22 23:25 UTC, kwcantrell commented on empress/support_files/js/colorer.js
> +    Colorer.__prOrGr = ["#008000", "#fed8b1", "#800080"];
good catch! I'll change them.

2021-02-23 02:00 UTC, fedarko reviewed
Sorry to nitpick but I have one more suggestion (I don't think it's needed but it will probably cause confusion if left unfixed). Aside from that, this looks good!

2021-02-23 02:00 UTC, fedarko commented on empress/support_files/js/colorer.js
> +    Colorer.__GR_OR_PR = "GnOrPr";
```suggestion
    Colorer.__GN_OR_PR = "GnOrPr";
```

Just to make this consistent with `Colorer.__gnOrPr` -- if we use different abbreviations i suspect it'll cause problems down the line

2021-02-23 02:00 UTC, fedarko commented on empress/support_files/js/colorer.js
> +        if (this.color === Colorer.__GR_OR_PR) {
```suggestion
        if (this.color === Colorer.__GN_OR_PR) {
```

2021-02-23 02:00 UTC, fedarko commented on empress/support_files/js/colorer.js
> +        if (this.color === Colorer.__GR_OR_PR) {
```suggestion
        if (this.color === Colorer.__GN_OR_PR) {
```

2021-02-23 02:44 UTC, kwcantrell commented
> Sorry to nitpick but I have one more suggestion (I don't think it's needed but it will probably cause confusion if left unfixed). Aside from that, this looks good!

Nitpick away :)

It should be fixed now.

2021-02-23 02:51 UTC, fedarko commented
Perfect, thanks so much!

2021-02-23 02:51 UTC, merged