Fixes error when no feature metadata file is provided
biocore/empress pull request #485
Opened 2021-02-12 01:44 UTC by ahdilmore

When I previously ran empress without supplying a feature metadata file, I received the error "All objects passed were None." This occurs on line 167 when pandas attempts to concatenate two Nones. I added a line to check whether both self.tip_md and self.int_md are both None to avoid raising the error.

2021-02-12 02:22 UTC, ElDeveloper requested changes
Thanks @ahdilmore! Would you be able to add a new test-case that without the changes reproduces the error, and with the changes in place passes? I left one suggestion which should take care of the failing build.

2021-02-12 02:22 UTC, ElDeveloper commented on empress/core.py
> +                if (self.tip_md is None) and (self.int_md is None):
Parenthesis are not needed here, and the PEP-8 linter will error:

```suggestion
                if self.tip_md is None and self.int_md is None: 
```

2021-02-17 02:16 UTC, ElDeveloper approved these changes
Thanks so much @ahdilmore

2021-02-17 05:49 UTC, fedarko requested changes
Thanks for catching this, @ahdilmore! I have a few suggestions that I think will improve the test you added -- please let me know if you have any questions.

2021-02-17 05:49 UTC, fedarko commented on tests/python/test_core.py
> +                      ordination=self.pcoa, shear_to_table=False)
```suggestion
                      ordination=self.biplot, shear_to_table=False)
```
From some manual testing, it looks like the bug you discovered (thank you!) only appears when a biplot is passed as the ordination -- a normal ordination without features (like `self.pcoa`) doesn't seem to trigger this problem (but please correct me if I've misunderstood this).

Therefore I think it would make sense to use a biplot in this test.

2021-02-17 05:49 UTC, fedarko commented on tests/python/test_core.py
> +        but empress itself does not'''
Could you please move this docstring to the top of this function (above the `viz = Empress...` line)?

2021-02-17 05:49 UTC, fedarko commented on tests/python/test_core.py
> +        self.assertIsNone(viz.features)
Sorry, I am not sure I understand these lines of code. Since the `All objects passed were None.` error was being triggered when creating an `Empress` object (which this test already does), I think we can remove these lines and the test should still be ok. (But again, please let me know if I'm missing something!)

2021-02-17 18:14 UTC, ahdilmore commented on tests/python/test_core.py
> +                      ordination=self.pcoa, shear_to_table=False)
Yes, you're correct, thank you!!

2021-02-17 18:30 UTC, ahdilmore commented on tests/python/test_core.py
> +        self.assertIsNone(viz.features)
I think that the line you added above is redundant with this. 

This line was intended to ensure that the feature_metadata stayed empty even when the ordination had features. In the unmodified code, we received an error concatenating two empty objects when the ordination has features. Line 252 was intended to check that the error was not raised. 

Like you said, I think now that line 248 has been changed, this can be removed.

2021-02-17 19:20 UTC, ahdilmore commented on tests/python/test_core.py
> +        self.assertIsNone(viz.features)
While the test is in essence to ensure that the Empress object is created, I'm going to keep line 252 to avoid failing style checks raised when the Empress object is created but not used.

2021-02-18 01:54 UTC, fedarko commented on tests/python/test_core.py
> +        self.assertIsNone(viz.features)
Got it. This looks good right now, thanks! I think we could bypass those style checks by removing the `viz = ` part of line 249, but I think leaving just the `assertIsNone` in here makes sense. Thank you for following up on all of this!

2021-02-18 01:55 UTC, merged

2021-02-18 01:57 UTC, fedarko commented
Thanks @ahdilmore!

2021-02-18 02:00 UTC, ElDeveloper commented
Thanks @ahdilmore and @fedarko 🎉

On (Feb-17-21|17:57), Marcus Fedarko wrote:
>Thanks @ahdilmore!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://urldefense.com/v3/__https://github.com/biocore/empress/pull/485*issuecomment-780983687__;Iw!!Mih3wA!WRqztNMdakAdVsvOWH9pUqX5XOpQSkC-knPULsW6gi8iWnxkMdGcuzAEKVjxl8Q$