Node default
biocore/empress pull request #486
Opened 2021-02-16 23:30 UTC by kwcantrell

This PR address #479

2021-02-17 02:14 UTC, ElDeveloper requested changes
@kwcantrell, thanks so much. This looks good but I think we can reduce the number of circles drawn. Instead of drawing all internal node circles, just show node circles for internal nodes that have only 1 descendant. This will help avoid issues where a branch looks "long" but is really a series of nodes one after the other. It will also reduce overhead by default drawing even fewer nodes.

See the example I posted [here](https://github.com/biocore/empress/issues/479) you'll see there's a few branches with a lot of internal nodes that have only one descendant.

2021-02-17 02:14 UTC, ElDeveloper commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
This is pseudo-code but I think this would help further reduce the number of circles drawn on screen:

```suggestion
                    visible(node) && !tree.isleaf(tree.postorderselect(node)) && tree.children(...).length === 1```

2021-02-17 23:57 UTC, kwcantrell commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
I added a forth option (show internal nodes with one descendant) and made it the default. Here is an example.
![Screenshot from 2021-02-17 15-54-45](https://user-images.githubusercontent.com/28127694/108283762-bd1f8980-7138-11eb-9c83-f6ed10f1e524.png)

2021-02-18 01:39 UTC, ElDeveloper commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
Excellent, that looks exactly like what we need! Just for completeness how does that clade in the tree look when you show all node circles?

2021-02-18 01:55 UTC, kwcantrell commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
Here is the clade. The node highlighted in the above clade is located on the bottom branch.

![Screenshot from 2021-02-17 17-54-22](https://user-images.githubusercontent.com/28127694/108292605-3de68180-7149-11eb-9c04-443096e1a017.png)

2021-02-18 02:00 UTC, ElDeveloper commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
Perfect, this looks great! Whenever you get a chance feel free to push the code and I'll be happy to re-review the code.

2021-02-18 02:02 UTC, kwcantrell commented on empress/support_files/js/empress.js
> +                    visible(node) && !tree.isleaf(tree.postorderselect(node))
my bad. I had commited it but forgot to push it.

2021-02-18 02:25 UTC, ElDeveloper approved these changes
The result is perfect! I tried it out in a tree and it looks great. Just a couple of comments regarding the tests and comments.

2021-02-18 02:25 UTC, ElDeveloper commented on tests/test-empress.js
> +            this.empress.drawNodeCircles = 0;
Can you add a test for the case where this value is 3 i.e. the default?

2021-02-18 02:25 UTC, ElDeveloper commented on empress/support_files/js/empress.js
> +     *                              2 - hide all node circles
Can you add the missing value here?

2021-02-18 02:25 UTC, ElDeveloper commented on empress/support_files/js/empress.js
> +        if (this.drawNodeCircles === 0) {
Can you add a comment before each `if` describing what case this is?

2021-02-18 19:02 UTC, kwcantrell commented on tests/test-empress.js
> +            this.empress.drawNodeCircles = 0;
test added

2021-02-18 19:03 UTC, kwcantrell commented on empress/support_files/js/empress.js
> +     *                              2 - hide all node circles
added missing value

2021-02-18 19:03 UTC, kwcantrell commented on empress/support_files/js/empress.js
> +        if (this.drawNodeCircles === 0) {
add comment to each if case

2021-02-18 19:03 UTC, kwcantrell commented
thanks @ElDeveloper! The PR should be good to merge in now.

2021-02-18 19:35 UTC, ElDeveloper approved these changes
This looks great, thanks so much @kwcantrell!

2021-02-18 19:35 UTC, merged