Dynamic bp tree
biocore/empress pull request #490
Opened 2021-03-01 23:27 UTC by kwcantrell

This PR implements a shear method for the bp tree that is based on https://github.com/wasade/improved-octo-waddle/blob/master/bp/_bp.pyx#L732

@wasade if you can take a look at this that would be awesome!

2021-03-02 00:10 UTC, ElDeveloper requested changes
Looks great @kwcantrell, I just added a few small comments.

2021-03-02 00:10 UTC, ElDeveloper commented on tests/test-bp-tree.js
> +        });
@kwcantrell can you add a test case for when all tips are removed?

2021-03-02 00:10 UTC, ElDeveloper commented on empress/support_files/js/bp-tree.js
> +
```suggestion
```

2021-03-02 00:10 UTC, ElDeveloper commented on empress/support_files/js/bp-tree.js
> +     * tips - Set
Can you fill the rest of the documentation?

2021-03-10 02:01 UTC, wasade commented
This looks awesome!!! +1

2021-03-10 21:23 UTC, kwcantrell commented on empress/support_files/js/bp-tree.js
> +     * tips - Set
doc added

2021-03-10 21:23 UTC, kwcantrell commented on tests/test-bp-tree.js
> +        });
test added

2021-03-10 21:51 UTC, ElDeveloper approved these changes

2021-03-10 21:51 UTC, ElDeveloper commented on empress/support_files/js/bp-tree.js
> +     * https://github.com/wasade/improved-octo-waddle/blob/master/bp/_bp.pyx#L732
Assuming this was based on the current tip of the main repo:

```suggestion
     * https://github.com/wasade/improved-octo-waddle/blob/master/bp/_bp.pyx#L732
     * SHA: ac16703d2e00eb0abb560a647bff32be120311e1
```

2021-03-10 21:51 UTC, ElDeveloper commented
Thanks @kwcantrell

2021-03-10 21:51 UTC, merged