added flag to make-dev-page so that only tree plot is created
biocore/empress pull request #530
Opened 2021-07-08 20:37 UTC by kwcantrell

This PR adds a `--no-empire` flag to the `make-dev-page` script which will result in a tree plot being created instead of an empire plot.

2021-07-12 15:50 UTC, ElDeveloper approved these changes
Looks great! :+1:

2021-07-28 22:58 UTC, ElDeveloper commented
@fedarko you requested a review from yourself, would you be able to review this PR when you get a chance?

2021-07-28 23:01 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F530%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F530%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F530%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F530%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F530%2Fplain.qzv)

2021-07-30 00:27 UTC, fedarko requested changes
I have a few small suggestions for making the documentation clearer, but aside from that this is super useful (this'll be really helpful for testing). Thanks @kwcantrell!

2021-07-30 00:27 UTC, fedarko commented on tests/python/util.py
> +        If False, will return None in place of an ordination
```suggestion
        If False, will return None in place of an ordination.
```

2021-07-30 00:27 UTC, fedarko commented on tests/python/make-dev-page.py
> +    other arguments are used.
GitHub is being a bit weird, but I propose replacing this entire paragraph with the following text:

```
    If any of the tree, table, or sample metadata are not provided, then
    the moving pictures dataset will be loaded. The --is-empire / --no-empire
    flag can be used in this case to alter whether the moving pictures dataset
    with or without an ordination is included.

    If all of the tree, table, and sample metadata are provided, then
    this dataset will be loaded.
```

I have removed the sentence about `--no-empire` causing a tree plot when no other arguments are being used, because this seems incorrect (the default moving pictures dataset includes sample metadata and a table).

2021-08-03 16:06 UTC, kwcantrell commented
@fedarko should be good to merge after tests finish running.

2021-08-05 23:02 UTC, fedarko commented on tests/python/test_core.py
> +        # set is_emipre_plot flag to True since DICT_A sets it as False (all
```suggestion
        # set is_empire_plot flag to True since DICT_A sets it as False (all
```

2021-08-05 23:03 UTC, fedarko approved these changes
LGTM (just fixed a small typo). will merge in a few minutes after the build finishes.

2021-08-05 23:15 UTC, merged