changed control to empress-control
biocore/empress pull request #541
Opened 2021-07-31 17:09 UTC by 1Harshini

changed control to empress-control

2021-07-31 19:10 UTC, emperor-helper commented
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F541%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F541%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F541%2Fempress-tree.qzv), [just-fm.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F541%2Fjust-fm.qzv), [plain.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F541%2Fplain.qzv)

2021-07-31 20:21 UTC, fedarko requested changes
Thank you, @1Harshini!

I have two small requests:

1. The use of `.control` at [Line 673](https://github.com/biocore/empress/blob/90a1d5772a9980556c384f0274a412b28eca5c00/empress/support_files/css/empress.css#L673) in `empress.css` should also be changed to `.empress-control`.

2. One of the changes made to the title text of a button in `side-panel.html` (`"Hide empress-control panel"`) should be changed back to just `"Hide control panel"`. I have suggested this using GitHub's interface.

Thank you again for the PR!

2021-07-31 20:21 UTC, fedarko commented on empress/support_files/templates/side-panel.html
> +    <button id="hide-ctrl" title="Hide empress-control panel"
```suggestion
    <button id="hide-ctrl" title="Hide control panel"
```

Since this is a message the user will see.

2021-08-02 20:04 UTC, merged

2021-08-02 20:04 UTC, fedarko commented
Thanks @1Harshini!

2021-08-02 20:10 UTC, ElDeveloper commented
Thanks both!

> On Aug 2, 2021, at 1:04 PM, Marcus Fedarko ***@***.***> wrote:
> 
> 
> Thanks @1Harshini!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>